### ISSUE TITLE
TypeScript definitions?

### ISSUE THREAD

**Issue by ezBeanie** [heavysixer/node-pptx#117]
Is there any way to use this library in typescript?

**Comment by JClackett** [comment]
Doesn't look like it unfortunately, no @types/node-pptx either, so probably have to manually declare types in own project

**Comment by ezBeanie** [comment]
Thanks!
Sadly i have never written my own types as of yet, but i think i will try to do so.
Do you know any ressource or tutorial which i could follow?
Thanks for the answer!

**Comment by JClackett** [comment]
Am working on this: 

```ts
declare module "nodejs-pptx" {
  declare interface Slide {
    addSlide(options?: any): Slide;
  }
  export class Composer {
    public load(path: string): Promise<Slide>
    public compose: (callback: (pres: Slide) => Promise<void>) => Promise<void>;
    public addSlide(): Slide
    public save(path: string): Promise<void>
  }
}
```

Im going to just add types for the methods that I need but you can follow a similar format, also literally just started so haven't tested anything yet but you get the idea!

**Comment by ezBeanie** [comment]
Wow, thanks! Thanks more than enough for me to continue!
