### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by taurn2edsense** [heavysixer/node-pptx#39]
I got this error while installing it.

 Error: Can't find Python executable "python", you can set the PYTHON env variable.

.. I tried few things like i tried to set python env variables but no use.

Please suggest a fix.
![error](https://user-images.githubusercontent.com/51396048/58950539-ac847f80-87ac-11e9-9710-1603f00f51c6.png)

**Comment by heavysixer** [comment]
This is not our package unfortunately. The `node-pptx` npm package is someone else's implementation.

**Comment by heavysixer** [comment]
I've updated the readme to point to the correct package: `npm i nodejs-pptx`

Sorry for the confusion!

**Comment by vcheeze** [comment]
I think the new `npm i nodejs-pptx` is now installing correctly. Currently, I only see **index.js**, the **license** file, **package.json**, and **readme.md** after I run the install, so the node's cjs loader is throwing the error './lib/pptx' not found, which is what **index.js** is importing. Can you please check and resolve this? Thanks!

**Comment by textminer** [comment]
Hi @vcheeze, I have the same issue. How did you solve it? since this issue is closed, I guess there's a solution.

Thanks

**Comment by gregdolley** [comment]
> I think the new `npm i nodejs-pptx` is now installing correctly. Currently, I only see **index.js**, the **license** file, **package.json**, and **readme.md** after I run the install, so the node's cjs loader is throwing the error './lib/pptx' not found when I `require('nodejs-pptx')`. Can you please check and resolve this?
> By the way, this is an awesome module. Thanks @heavysixer :)



> Hi @vcheeze, I have the same issue. How did you solve it? since this issue is closed, I guess there's a solution.
> 
> Thanks

@vcheeze @textminer - This issue has since been fixed. Please try pulling the latest and running "npm install" again. You should get all the files this time.
