### ISSUE TITLE
npm package not installing correctly

### ISSUE THREAD

**Issue by vcheeze** [heavysixer/node-pptx#40]
`npm i nodejs-pptx` doesn't seem to install all the correct files. Right now I see **index.js**, the **license** file, **package.json**, and **readme.md**. 
Can you please check/fix this? Thank you!

**Comment by isklikas** [comment]
Happens to me too!

**Comment by gregdolley** [comment]
@vcheeze @isklikas I have updated the package.json file to include the missing /lib folder. Please try installing again. It should work now.
