### ISSUE TITLE
await is only valid in async function

### ISSUE THREAD

**Issue by KimSeongheon678** [heavysixer/node-pptx#50]
when i folow examples , i have some issues that ' i cant use await becuz it can be used only in async function' but i saw that node-pptx is sync funtion,,, 
so how  can i use await like you used in examples??

**Comment by pitust** [comment]
do this:
```javascript
async function main() {
// Your code here
}
main();
```

**Comment by heavysixer** [comment]
please reopen this issue if you need more help.
