### ISSUE TITLE
Load PPTX through Buffer

### ISSUE THREAD

**Issue by joseantoniosagredo** [heavysixer/node-pptx#53]

**Comment by gregdolley** [comment]
@joseantoniosagredo - Um, no description??? I'm guessing you want functionality where you can load an existing pptx via a Buffer object containing the pptx data instead of loading from disk??

**Comment by heavysixer** [comment]
Please reopen this issue with a description. Additionally, if you would like to propose a feature we're happy to accept pull requests :-)

**Comment by joseantoniosagredo** [comment]
Hi! sorry so much! i didn't see the last message. I have just added a descriptions issue. 
Thanks!
