### ISSUE TITLE
npm package not updated?

### ISSUE THREAD

**Issue by MikeHingley22** [heavysixer/node-pptx#97]
looking at the NPM packages I can see the following : 

![image](https://user-images.githubusercontent.com/99718263/179475848-8e30abd4-3ce6-4893-88c8-103b845e9d98.png)

but github shows a latest version of 2021.

![image](https://user-images.githubusercontent.com/99718263/179475945-e76a2b22-345f-4f57-a20d-db52e33080a7.png)

Can I suggest pushing out the updates to NPM, or updating the installation instructions to load the release from Github?

**Comment by lillijo** [comment]
Hi, it would be great if you could update the npm package indeed!

**Comment by jboler** [comment]
1.2.3 released!
